generally/urls.py
from django.urls import path
from .views import HomeView, Filtered, CheckoutView, CartView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('filtered/', Filtered.as_view(), name='filtered'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('cart/', CartView.as_view(), name='cart'),

]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard')),
    path('admin/', admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    # path('', include('tyres.urls')),
    path('', include('generally.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tyres/urls.py
from django.urls import path

# urlpatterns = [
#     path(),
# ]

tyres/models.py
from django.db import models
# from django_countries.fields import CountryField

from django.contrib.contenttypes.fields import GenericRelation
from .helps import orded_status


# from star_ratings.models import Rating


# Create your models here.
class CarMarka(models.Model):
    marka = models.CharField(max_length=50, verbose_name='Marka')

    def __str__(self):
        return self.marka


class CarModel(models.Model):
    marka = models.ForeignKey(CarMarka, on_delete=models.CASCADE, verbose_name='Marka')
    model = models.CharField(max_length=50, verbose_name='Model')

    def __str__(self):
        return self.model


class CarMotor(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, verbose_name='Model')
    motor = models.CharField(max_length=50, verbose_name='Motor')

    def __str__(self):
        return self.motor


class CarYear(models.Model):
    motor = models.ForeignKey(CarMotor, on_delete=models.CASCADE, verbose_name='Motor')
    year = models.PositiveIntegerField(verbose_name='İl')

    def __str__(self):
        return str(self.year)


class Car(models.Model):
    marka = models.ForeignKey(CarMarka, on_delete=models.CASCADE, null=True, verbose_name='Maşının Markası')
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, null=True, verbose_name='Maşının Modeli')
    motor = models.ForeignKey(CarMotor, on_delete=models.CASCADE, null=True, verbose_name='Maşının Motoru')
    car_year = models.ForeignKey(CarYear, on_delete=models.CASCADE, null=True, verbose_name='Maşının İli')

    def __str__(self):
        return self.marka.marka + ' ' + self.model.model + ' ' + self.motor.motor


class Brand(models.Model):
    brand = models.CharField(max_length=64, verbose_name='Brend')
    img = models.ImageField(upload_to='brand/', null=True)

    def __str__(self):
        return self.brand


class Tyres(models.Model):
    car = models.ManyToManyField(Car)
    # category = models.IntegerField(choices=Category)
    width = models.CharField(max_length=64, verbose_name='En (mm)')
    height = models.CharField(max_length=64, verbose_name='Hündürluk (%)')
    radius = models.CharField(max_length=64, verbose_name='Radius (düym)')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)

    klass = models.CharField(max_length=64, verbose_name='Klass')
    price = models.FloatField(verbose_name='Qiymət')
    year = models.PositiveIntegerField(verbose_name='İl')
    country = models.CharField(max_length=64, verbose_name='Ölkə')
    name = models.CharField(max_length=128, verbose_name='Ad')
    published = models.BooleanField(default=False, verbose_name='published')

    def __str__(self):
        return self.name


class TyresImage(models.Model):
    trye = models.ForeignKey(Tyres, on_delete=models.CASCADE, verbose_name='Təkərin')
    images = models.ImageField(upload_to='tyres/', verbose_name='Şəkil')

    def __str__(self):
        return self.trye.name

    def get_image(self):
        return self.images

# class OrderList(models.Model):
#     product = models.ForeignKey(Tyres, on_delete=models.CASCADE)
#     # add_to_card = models.BooleanField(default=False)
#     total_price = models.PositiveIntegerField(default=0)
#     quantity = models.PositiveIntegerField(default=0, null=True)
#     # total_list = models.PositiveIntegerField(default=0)
#     create_date = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.product.name

generally/forms.py
from django import forms
from .models import LetterEmail


class LetterEForm(forms.ModelForm):
    class Meta:
        model = LetterEmail
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={
                'name': 'NewsLetter',
                'type': 'text',
                'class': 'footer-newsletter__form-input',
                'id': 'footer-newsletter-address',
                'placeholder': 'Email Address...',
            })
        }

generally/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from django.utils import timezone
from django.views import generic
from django.views.generic.base import ContextMixin

from .models import Unique, FirstMenu, \
    SecondMenu, FooterMenu, FooterSubMenu, Newsletter, \
    Social, SocialText, SlideImage, Client, FeaturedBlocks, \
    Discount, DiscountProducts

from tyres.models import CarMarka, CarModel, CarMotor, \
    CarYear, Tyres, Brand
from orders.models import Card_list, OrderProducts
from .forms import LetterEForm
from orders.forms import OrderForm


# Create your views here.


class CommonMixin(ContextMixin):

    def get_context_data(self, **kwargs):
        context = super(CommonMixin, self).get_context_data(**kwargs)
        context['unique'] = Unique.objects.last()
        context['block'] = FeaturedBlocks.objects.all()
        context['first_menu'] = FirstMenu.objects.all()
        context['second_menu'] = SecondMenu.objects.all()
        context['footer_menu'] = FooterMenu.objects.all()
        context['footer_sub_menu'] = FooterSubMenu.objects.all()
        context['newsletter'] = Newsletter.objects.last()
        context['social_text'] = SocialText.objects.last()
        context['social'] = Social.objects.all()
        context['slide'] = SlideImage.objects.all()
        context['brands'] = Brand.objects.all()
        context['products'] = Tyres.objects.all()
        context['last_products'] = Tyres.objects.all().order_by('-id')[:5]

        context['tyres_width'] = Tyres.objects.values_list('width', flat=True).distinct()
        context['tyres_height'] = Tyres.objects.values_list('height', flat=True).distinct()
        context['tyres_radius'] = Tyres.objects.values_list('radius', flat=True).distinct()

        user = self.request.session.session_key
        cards = Card_list.objects.filter(user__session_key=user)
        context['order'] = cards
        my_list = []
        for items in cards:
            total = items.total_price
            my_list.append(total)
        context['total'] = sum(my_list)
        context['count'] = len(my_list)

        return context


class Filtered(CommonMixin, generic.ListView):
    template_name = 'shop-list.html'
    context_object_name = 'filter'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(Filtered, self).get_context_data(**kwargs)
        context['checked_brand'] = self.request.GET.getlist('brand[]')
        context['checked_width'] = self.request.GET.getlist('width[]')
        context['checked_height'] = self.request.GET.getlist('height[]')
        context['checked_radius'] = self.request.GET.getlist('radius[]')

        return context

    def post(self, request):
        if self.request.is_ajax():
            if self.request.POST.get('namee') == 'remove':
                data_id = self.request.POST.get('item_id')
                tyres = Tyres.objects.filter(id=data_id).last()
                card_list = Card_list.objects.filter(product_id=data_id).last()
                if tyres:
                    tyres.add_to_card = False
                    card_list.quantity = 0
                    tyres.save()
                    card_list.delete()
            elif self.request.POST.get('namee') == 'add_to_cart':
                session = self.request.session.session_key
                data_id = self.request.POST.get('data_id')
                tyres = Tyres.objects.filter(id=data_id).first()
                card_list = Card_list.objects.filter(product_id=data_id).first()
                client = Client.objects.filter(session_key=session).first()

                if not client:
                    Client.objects.create(
                        session_key=session
                    )

                client = Client.objects.filter(session_key=session).first()
                card = Card_list.objects.filter(product_id=data_id, user=client).first()
                if not card:
                    Card_list.objects.create(
                        product_id=data_id,
                        quantity=1,
                        user_id=client.id,
                        total_price=tyres.price,
                    )
                    tyres.add_to_card = True
                    tyres.save()
                else:
                    card_list.quantity += 1
                    card_list.total_price = tyres.price * card_list.quantity
                    card_list.save()

    def get_queryset(self):
        query = Tyres.objects.all()
        model = self.request.GET.get('model')
        marka = self.request.GET.get('marka')
        motor = self.request.GET.get('motor')
        elements = self.request.GET

        if 'marka' and 'model' and 'motor' and 'year' in self.request.GET:
            query = query.filter(
                Q(car__marka__marka=marka) &
                Q(car__model__model=model) &
                Q(car__motor__motor=motor)
            )

        if 'brand[]' in elements:
            query = query.filter(brand__brand__in=elements.getlist('brand[]'))

        if 'width[]' in elements:
            query = query.filter(width__in=elements.getlist('width[]'))

        if 'height[]' in elements:
            query = query.filter(height__in=elements.getlist('height[]'))

        if 'radius[]' in elements:
            query = query.filter(radius__in=elements.getlist('radius[]'))

        if "ASC" in elements:
            return query.order_by('price')
        else:
            return query.order_by('-price')

        return query


class HomeView(CommonMixin, generic.TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['marka'] = CarMarka.objects.all()
        context['model'] = CarModel.objects.all()
        context['motor'] = CarMotor.objects.all()
        context['year'] = CarYear.objects.all()
        context['brands'] = Brand.objects.all()
        context['letter_form'] = LetterEForm()
        context['new_arrivals'] = Tyres.objects.all().order_by('-id')[:8]
        discount = Discount.objects.all()
        expiry_date = discount.values_list('expiry_date', flat=True)
        current_date = timezone.now()
        for date in expiry_date:
            context['discount'] = discount.filter(expiry_date__range=[current_date, date])
            filters = discount.filter(expiry_date__range=[current_date, date]).values('discount_name')
            # print(filters)
            # for i in filters:
            #     print(i)
            discount_products = Tyres.objects.filter(product__diccount__discount_name='Qelebe')
            print(discount_products)
            # print(Tyres.objects.filter(product__diccount__discount_name='Qelebe'))

            context['discount_products'] = discount_products
        return context

    def post(self, request):
        if self.request.POST.get('namee') == 'remove':
            print('REMOVEE')
            data_id = self.request.POST.get('item_id')
            tyres = Tyres.objects.filter(id=data_id).last()
            card_list = Card_list.objects.filter(product_id=data_id).last()
            if tyres:
                tyres.add_to_card = False
                card_list.quantity = 0
                tyres.save()
                card_list.delete()

        if 'email' in self.request.POST:
            form = LetterEForm(self.request.POST)
            if form.is_valid():
                form.save()

        else:
            marka_id = self.request.POST.get('marka_id')
            model_id = self.request.POST.get('model_id')
            motor_id = self.request.POST.get('motor_id')
            model = CarModel.objects.filter(marka_id=marka_id)
            motor = CarMotor.objects.filter(model_id=model_id)
            year = CarYear.objects.filter(motor_id=motor_id)
            result = []

            for i in model:
                result.append({
                    'model': i.model,
                    'id': i.id
                })

            for i in motor:
                result.append({
                    'motor': i.motor,
                    'id': i.id
                })
            for i in year:
                result.append({
                    "year": i.year,
                    'id': i.id
                })

            return JsonResponse({
                'data': result
            })


class CheckoutView(CommonMixin, generic.CreateView):
    template_name = 'checkout.html'
    model = OrderProducts
    success_url = "/"
    form_class = OrderForm

    def form_valid(self, form):
        user = self.request.session.session_key
        cards = Card_list.objects.filter(user__session_key=user)
        form.save()
        for card_item in cards:
            OrderProducts.objects.create(
                product_name=card_item.product.name,
                quantity=card_item.quantity,
                total_price=card_item.total_price,
                order=form.instance
            )
            cards.delete()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order_form'] = OrderForm()
        user = self.request.session.session_key
        cards = Card_list.objects.filter(user__session_key=user)
        context['order'] = cards
        my_list = []
        for items in cards:
            total = items.total_price
            my_list.append(total)
        context['total'] = sum(my_list)
        return context


class CartView(CommonMixin, generic.ListView):
    template_name = 'cart.html'

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        user = self.request.session.session_key
        card_products = Card_list.objects.filter(user__session_key=user)
        context['card_list'] = card_products

generally/templates/cart.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="site__body">
        <div class="block-header block-header--has-breadcrumb block-header--has-title">
            <div class="container">
                <div class="block-header__body">
                    <h1 class="block-header__title">Shopping Cart</h1>
                </div>
            </div>
        </div>
        <div class="block">
            <div class="container">
                <div class="cart">
                    <div class="cart__table cart-table">
                        <table class="cart-table__table">
                            <thead class="cart-table__head">
                            <tr class="cart-table__row">
                                <th class="cart-table__column cart-table__column--image">Image</th>
                                <th class="cart-table__column cart-table__column--product">Product</th>
                                <th class="cart-table__column cart-table__column--price">Price</th>
                                <th class="cart-table__column cart-table__column--quantity">Quantity</th>
                                <th class="cart-table__column cart-table__column--total">Total</th>
                                <th class="cart-table__column cart-table__column--remove"></th>
                            </tr>
                            </thead>
                            <tbody class="cart-table__body">
                            {% for list in card_list %}
                                <tr class="cart-table__row">
                                    <td class="cart-table__column cart-table__column--image">
                                        <div class="image image--type--product">
                                            <a href="product-full.html" class="image__body">
                                                <img class="image__tag"
                                                     src="{{ list.product.tyresimage_set.last.images.url }}"
                                                     alt="">
                                            </a>
                                        </div>
                                    </td>
                                    <td class="cart-table__column cart-table__column--product">
                                        <a href="" class="cart-table__product-name">{{ list.product.name }}</a>
                                        <ul class="cart-table__options">
                                            <li>Width: {{ list.product.width }}</li>
                                            <li>Height: {{ list.product.height }}</li>
                                            <li>Radius: {{ list.product.radius }}</li>
                                        </ul>
                                    </td>
                                    <td class="cart-table__column cart-table__column--price" data-title="Price">
                                        {{ list.product.price }}
                                    </td>
                                    <td class="cart-table__column cart-table__column--quantity" data-title="Quantity">
                                        <div class="cart-table__quantity input-number">
                                            <form method="POST">
                                                {% csrf_token %}
                                                <input price-data="{{ list.product.price }}"
                                                       quantity-data="{{ list.product_id }}"
                                                       name="quantity"
                                                       class="form-control input-number__input quantity"
                                                       min="1" type="submit"
                                                       value="{{ list.quantity }}"></form>
                                            <div class="input-number__add"></div>
                                            <div class="input-number__sub"></div>
                                        </div>
                                    </td>
                                    <td data-price="{{ list.total_price }}" data-id="{{ list.product_id }}"
                                        class="cart-table__column cart-table__column--total total total_price"
                                        data-title="Total">
                                        {{ list.total_price }} AZN
                                    </td>
                                    <td class="cart-table__column cart-table__column--remove">
                                        <form method="POST">
                                            {% csrf_token %}
                                            <button name="remove" data-id="{{ list.product_id }}" type="button"
                                                    class="cart-table__remove btn btn-sm btn-icon btn-muted">
                                                <svg width="12" height="12">
                                                    <path d="M10.8,10.8L10.8,10.8c-0.4,0.4-1,0.4-1.4,0L6,7.4l-3.4,3.4c-0.4,0.4-1,0.4-1.4,0l0,0c-0.4-0.4-0.4-1,0-1.4L4.6,6L1.2,2.6
	c-0.4-0.4-0.4-1,0-1.4l0,0c0.4-0.4,1-0.4,1.4,0L6,4.6l3.4-3.4c0.4-0.4,1-0.4,1.4,0l0,0c0.4,0.4,0.4,1,0,1.4L7.4,6l3.4,3.4
	C11.2,9.8,11.2,10.4,10.8,10.8z"/>
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <div class="cart__totals">
                        <div class="card">
                            <div class="card-body card-body--padding--2">
                                <h3 class="card-title">Cart Totals</h3>
                                <table class="cart__totals-table">

                                    <tr>
                                        <th>Total</th>
                                        <td>{{ total }} AZN</td>
                                    </tr>
                                </table>
                                <a class="btn btn-primary btn-xl btn-block" href="{% url 'checkout' %}">
                                    Proceed to checkout
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-space block-space--layout--before-footer"></div>
    </div>

{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {

            $('.quantity').change(function () {
                quantity = parseInt($(this).val())
                price = parseInt($(this).attr('price-data'))
                namee = $(this).attr('name')
                data_id = $(this).attr('quantity-data')
                $.ajax({
                    method: 'POST',
                    data: {
                        'quantity': quantity,
                        'namee': namee,
                        'price': price,
                        'data_id': data_id,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    success: function () {
                        location.reload()
                        console.log('success')
                    },
                    error: function () {
                        location.reload()
                        console.log('errorr')
                    }
                })
            })

        })
    </script>
{% endblock %}

generally/templates/checkout.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="site__body">
        <div class="block-header block-header--has-breadcrumb block-header--has-title">
            <div class="container">
                <div class="block-header__body">
                    <h1 class="block-header__title">Checkout</h1>
                </div>
            </div>
        </div>
        <div class="checkout block">
            <div class="container container--max--xl">
                <div class="row">
                    <div class="col-12 col-lg-6 col-xl-7">
                        <div class="card mb-lg-0">
                            <div class="card-body card-body--padding--2">
                                <h3 class="card-title">Billing details</h3>
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-row">

                                        {% for form in order_form %}
                                            <div class="form-group col-md-6">
                                                <label for="{{ form.id_for_label }}">{{ form.label }}</label>
                                                {{ form }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-xl btn-block">Order</button>
                                </form>
                            </div>
                            <div class="card-divider"></div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-6 col-xl-5 mt-4 mt-lg-0">
                        <div class="card mb-0">
                            <div class="card-body card-body--padding--2">
                                <h3 class="card-title">Your Order</h3>
                                <table class="checkout__totals">
                                    <thead class="checkout__totals-header">
                                    <tr>
                                        <th>Product</th>
                                        <th>Total</th>
                                    </tr>
                                    </thead>
                                    <tbody class="checkout__totals-products">
                                    {% for order_item in order %}
                                        <tr>
                                            <td>{{ order_item.product.name }} × {{ order_item.quantity }}</td>
                                            <td>{{ order_item.total_price }} AZN</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                    <tfoot class="checkout__totals-footer">
                                    <tr>
                                        <th>Total</th>
                                        <td>{{ total }} AZN</td>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-space block-space--layout--before-footer"></div>
    </div>
{% endblock %}